### ISSUE TITLE
All ITV Channels Down

### ISSUE THREAD

**Issue by Bapethoven** [ExperiencersInternational/tvsetup#1]
All respective ITV channels appear to be down, alternative source needed

**Comment by ExperiencersInternational** [comment]
I'm working on it, I'd recommend leaving the bug report I've already listed on https://github.com/iptv-org/iptv/issues/11351. I'm hoping we're able to get streams eventually, but if you need ITV 1, you mostly have it on Channel 910 which is STV, and still works due to being from a different source.

As soon as we get any updates there, I'll push changes here

**Comment by ExperiencersInternational** [comment]
Channels seem to now work. Issue closed.

![image](https://user-images.githubusercontent.com/56035537/214150637-9e76022e-2dde-485a-a2da-d3d4c69f9e5a.png)
